/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.ifba.tarefa.dao.DaoTarefa;
import br.com.ifba.tarefa.model.Tarefa;
import br.com.ifba.tarefa.service.IServiceTarefa;
import br.com.ifba.tarefa.service.ServiceTarefa;
import static java.awt.Color.white;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davia
 */
public class TelaAtualizar extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtualizar
     */
    
    public TelaAtualizar() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(white);
        mostarTarefa();
    }

    public TelaAtualizar(Long id) {
        this.id = id;
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(white);
        mostarTarefa();
    }
    
    
    private Long id;
    private String descricao;
    private String local;
    
    //GETTERS AND SETTERS

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getLocal() {
        return local;
    }

    public void setLocal(String local) {
        this.local = local;
    }
    
    public void mostarTarefa(){
        //ATRIBUI OS VALORES DA TAREFA SELECIONADA NA JTABLE AOS TEXTFIELD
        DaoTarefa tdao = new DaoTarefa();
        Tarefa tarefa = new Tarefa();
        
        tarefa = tdao.getById(id);
        setDescricao(tarefa.getDescricao());
        setLocal(tarefa.getLocal());
        
        lblMostrarId.setText(Long.toString(getId()));
        txtDescricao.setText(getDescricao());
        txtLocal.setText(getLocal());
        //---------------------------------------
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescricao = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        lblAtualizar = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblMostrarId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 0));
        lblDescricao.setText("Descrição");

        lblLocal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblLocal.setForeground(new java.awt.Color(0, 0, 0));
        lblLocal.setText("Local");

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(0, 0, 0));
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        txtLocal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtLocal.setForeground(new java.awt.Color(0, 0, 0));

        lblAtualizar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        lblAtualizar.setText("Atualizar Tarefa");

        btnConfirmar.setBackground(new java.awt.Color(0, 204, 0));
        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("ID");

        lblMostrarId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMostrarId.setForeground(new java.awt.Color(0, 0, 0));
        lblMostrarId.setText("mostrarID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblAtualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addComponent(lblLocal)
                            .addComponent(lblId))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDescricao)
                                .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMostrarId))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAtualizar)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblMostrarId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocal))
                .addGap(43, 43, 43)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
       /*ATRIBUI O CONTEUDO DOS TEXTFIEL E LblMostrarId A UM OBJETO TAREFA E
       ATUALIZA O MESMO NO BANCO DE DADOS*/
       Tarefa tarefa = new Tarefa();
       DaoTarefa tdao = new DaoTarefa();
       tarefa.setId(Long.valueOf(lblMostrarId.getText()));
       tarefa.setDescricao(txtDescricao.getText());
       tarefa.setLocal(txtLocal.getText());
       
       if(txtDescricao.getText().isEmpty() || txtLocal.getText().isEmpty()){
           JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
       }else{
            IServiceTarefa serviceTarefa = new ServiceTarefa();
            serviceTarefa.updateTarefa(tarefa);
       }
       
       
       //-------------------------------------------------
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblAtualizar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblMostrarId;
    private javax.swing.JTextField txtDescricao;
    public javax.swing.JTextField txtLocal;
    // End of variables declaration//GEN-END:variables
}
